server:
  port: 8080


super-mybatis:
  url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  username: root
  password: tiger
  driverclassname: com.mysql.cj.jdbc.Driver
  mapperpath: com.mybatis.demo.sys.mapper
  alias: com.mybatis.demo.sys.entity
  mapperlocations: classpath:mapper/**.xml
